image:
  file: .gitpod.Dockerfile
tasks:
- command: julia --version
- command: bash -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
- command: source ~/.bashrc
- init: make
    command: ./julia
vscode:
  extensions:
    - julialang.language-julia@0.12.3:lgRyBd8rjwUpMGG0C5GAig==
